version: '3.8'

services:
  auckland:
    container_name: auckland
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      env_file:
        .env
    volumes:
      - ./shared:/shared
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - postgres
    networks:
      - awesome
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      env_file:
        .env
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - '35000:5432'
    restart: always
    networks:
      - awesome
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      env_file:
        .env
    ports:
      - '8097:8097'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome

networks:
  awesome:
    driver: bridge
