version: '3.8'

services:
  auckland:
    container_name: auckland
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      env_file:
        .env
    volumes:
      - ./shared:/shared
    ports:
      - '3000:3000'
    restart: always
    networks:
      - awesome
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      env_file:
        ./prod.env
    ports:
      - '8097:8097'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - awesome

networks:
  awesome:
    driver: bridge
