# This is a basic workflow to help you get started with Actions

name: YC Deploy

concurrency: 
  group: production
  cancel-in-progress: true

# Controls when the workflow will run
on:
  release:
    types: [created]
    branches:
      - deploy

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v1.0.0
        with:
              yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpkmb8e6ut2s0us2l5k
          CR_REPOSITORY: aukland-game
          IMAGE_TAG: ${{ github.sha }}
        run: |
            docker-compose up -d --build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
            docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
